version: '3.4'

services:
  web:
    build: ./culinary_recipes
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./culinary_recipes/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./culinary_recipes/envs/.env
    depends_on: 
      - postgres
  postgres:    
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1123QwER
      POSTGRES_USER: postgres
      POSTGRES_DB: recipes_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  # redis:
  #   image: redis:7.0.5
  #   restart: always
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
